# Configuration Example for Recovery Grid Direction v3.1.0
# Simplified configuration for the refactored EA

# === Identity ===
magic: 990045  # CHANGE THIS for each instance!

# === Symbol Presets ===
symbol_preset: PRESET_AUTO  # AUTO, LOW_VOL, MEDIUM_VOL, HIGH_VOL, CUSTOM
use_tested_presets: true    # Use tested presets for EUR/XAU/GBP/JPY

# === Spacing Configuration ===
spacing_mode: HYBRID         # PIPS, ATR, or HYBRID
spacing_pips: 25.0          # Base spacing in pips
spacing_atr_mult: 0.6       # ATR multiplier (for ATR/HYBRID modes)
min_spacing_pips: 12.0      # Minimum spacing floor (HYBRID mode)
atr_period: 14
atr_timeframe: M15

# === Grid Configuration ===
grid_levels: 6              # Number of levels per side
lot_base: 0.01              # Base lot size (start small!)
lot_scale: 1.0              # 1.0 = flat, 2.0 = martingale

# === Profit Target ===
target_cycle_usd: 10.0      # Target profit per cycle (USD)

# === Risk Management ===
session_sl_usd: 10000       # Session stop loss (monitoring only - not enforced!)

# === Lazy Grid Fill (Always Enabled) ===
# No configuration needed - always on
initial_warm_levels: 2      # Initial pending levels
auto_max_level_distance: true  # Auto-calculate max distance
lazy_distance_multiplier: 20.0  # Spacing multiplier for auto mode
max_dd_for_expansion: -20.0     # Stop expanding if DD < this %

# === Dynamic Spacing (Always Enabled) ===
# No configuration needed - always on
dynamic_spacing_max: 3.0    # Max spacing multiplier
trend_timeframe: M15        # Timeframe for trend analysis

# === Time-Based Exit (CRITICAL - Enable for Production!) ===
time_exit_enabled: true     # MUST ENABLE for production!
time_exit_hours: 24         # Exit after 24h underwater
time_exit_max_loss: -100.0  # Max acceptable loss (USD)
time_exit_trend_only: true  # Only exit counter-trend positions

# === News Filter (Optional but Recommended) ===
news_filter_enabled: true
news_impact_filter: "High"  # High, Medium+, or All
news_buffer_minutes: 60     # Buffer before/after news

# === Execution Settings ===
order_cooldown_sec: 5       # Min seconds between orders
slippage_pips: 0            # Max slippage
respect_stops: false        # false for backtesting, true for live
commission_per_lot: 0.0     # For backtest PnL calculation only

# === Optional Features (Experimental) ===
trap_detection_enabled: false   # Trap detection (experimental)
quick_exit_enabled: false       # Quick exit mode (experimental)

# === Example Configurations by Symbol ===

# EURUSD (Conservative)
# spacing_pips: 25
# grid_levels: 10
# lot_base: 0.01
# target_cycle_usd: 5.0

# XAUUSD (High Volatility)
# spacing_pips: 150
# grid_levels: 5
# lot_base: 0.01
# target_cycle_usd: 20.0
# time_exit_max_loss: -100.0  # Critical for XAUUSD!

# GBPUSD (Medium)
# spacing_pips: 50
# grid_levels: 7
# lot_base: 0.01
# target_cycle_usd: 8.0

# === Important Notes ===
# 1. Always start with small lot sizes (0.01)
# 2. Test on demo for at least 2 weeks
# 3. Time-based exit is CRITICAL for production
# 4. Monitor account equity - no automated stop loss!
# 5. Strategy accepts losses during strong trends